POST http://127.0.0.1:5000/
Content-Type: application/json

{
  "title": "str",
  "content": "str",
  "author": "str",
  "project": "str",
  "target": "str",
  "private": false
}

###

GET http://127.0.0.1:5000/
Content-Type: application/json

{
  "title": "str",
  "content": "str",
  "author": "str",
  "project": "str",
  "target": "str",
  "private": false
}

<> 2020-01-07T113917.200.json
<> 2020-01-07T101526.500.html
<> 2020-01-07T101259.500.html

###