POST http://127.0.0.1:5000/
Content-Type: application/json

{
  "title": "str",
  "content": "str",
  "author": "str",
  "project": "str",
  "target": "str",
  "private": false
}

###

GET http://127.0.0.1:5000/
Content-Type: application/json

{
}

###

DELETE http://127.0.0.1:5000/LlDM3Jk

###